package main

import (
	"log"

	"github.com/hugonorte/chinesonline-go-api/internal/config"
	"github.com/hugonorte/chinesonline-go-api/internal/db"
	"github.com/hugonorte/chinesonline-go-api/internal/models"
)

func main() {
	// Carrega configurações (.env)
	cfg := config.LoadConfig()

	// Inicializa banco de dados
	if cfg.NeonDBUrl == "" {
		log.Fatalf("Erro: NEON_CONNECTION_STRING não definida. Não é possível rodar o seed.")
	}

	log.Println("Conectando ao banco de dados para iniciar o seed...")
	db.InitDB(cfg.NeonDBUrl)

	// Dados de seed: Ideogramas úteis de Nível 1
	seedData := []models.Ideogram{
		{Character: "一", PinyinWithoutTones: "yi", PinyinWithTones: "yī", PinyinWithNumericTones: "yi1", Translation: "Um", DifficultyLevel: 1},
		{Character: "五", PinyinWithoutTones: "wu", PinyinWithTones: "wǔ", PinyinWithNumericTones: "wu3", Translation: "Cinco", DifficultyLevel: 1},
		{Character: "八", PinyinWithoutTones: "ba", PinyinWithTones: "bā", PinyinWithNumericTones: "ba1", Translation: "Oito", DifficultyLevel: 1},
		{Character: "你", PinyinWithoutTones: "ni", PinyinWithTones: "nǐ", PinyinWithNumericTones: "ni3", Translation: "Você", DifficultyLevel: 1},
		{Character: "好", PinyinWithoutTones: "hao", PinyinWithTones: "hǎo", PinyinWithNumericTones: "hao3", Translation: "Bom", DifficultyLevel: 1},
		{Character: "二", PinyinWithoutTones: "er", PinyinWithTones: "èr", PinyinWithNumericTones: "er4", Translation: "Dois", DifficultyLevel: 2},
		{Character: "三", PinyinWithoutTones: "san", PinyinWithTones: "sān", PinyinWithNumericTones: "san1", Translation: "Três", DifficultyLevel: 2},
		{Character: "四", PinyinWithoutTones: "si", PinyinWithTones: "sì", PinyinWithNumericTones: "si4", Translation: "Quatro", DifficultyLevel: 2},
		{Character: "六", PinyinWithoutTones: "liu", PinyinWithTones: "liù", PinyinWithNumericTones: "liu4", Translation: "Seis", DifficultyLevel: 2},
		{Character: "七", PinyinWithoutTones: "qi", PinyinWithTones: "qī", PinyinWithNumericTones: "qi1", Translation: "Sete", DifficultyLevel: 2},
		{Character: "九", PinyinWithoutTones: "jiu", PinyinWithTones: "jiǔ", PinyinWithNumericTones: "jiu3", Translation: "Nove", DifficultyLevel: 2},
		{Character: "很", PinyinWithoutTones: "hen", PinyinWithTones: "hěn", PinyinWithNumericTones: "hen3", Translation: "Muito", DifficultyLevel: 2},
		{Character: "忙", PinyinWithoutTones: "mang", PinyinWithTones: "máng", PinyinWithNumericTones: "mang2", Translation: "Ocupado", DifficultyLevel: 2},
		{Character: "吗", PinyinWithoutTones: "ma", PinyinWithTones: "ma", PinyinWithNumericTones: "ma5", Translation: "Partícula interrogativa", DifficultyLevel: 2},
		{Character: "们", PinyinWithoutTones: "men", PinyinWithTones: "men", PinyinWithNumericTones: "men5", Translation: "Plural", DifficultyLevel: 2},
		{Character: "我", PinyinWithoutTones: "wo", PinyinWithTones: "wǒ", PinyinWithNumericTones: "wo3", Translation: "Eu", DifficultyLevel: 2},
		{Character: "我们", PinyinWithoutTones: "wo men", PinyinWithTones: "wǒ men", PinyinWithNumericTones: "wo3 men5", Translation: "Nós", DifficultyLevel: 2},
		{Character: "不", PinyinWithoutTones: "bu", PinyinWithTones: "bù", PinyinWithNumericTones: "bu4", Translation: "Não", DifficultyLevel: 2},
		{Character: "谢谢", PinyinWithoutTones: "xie xie", PinyinWithTones: "xiè xie", PinyinWithNumericTones: "xie4 xie5", Translation: "Obrigado", DifficultyLevel: 2},
		{Character: "不客气", PinyinWithoutTones: "bu ke qi", PinyinWithTones: "bú kè qì", PinyinWithNumericTones: "bu2 ke4 qi4", Translation: "De nada", DifficultyLevel: 2},
		{Character: "十", PinyinWithoutTones: "shi", PinyinWithTones: "shí", PinyinWithNumericTones: "shi2", Translation: "Dez", DifficultyLevel: 3},
		{Character: "是", PinyinWithoutTones: "shi", PinyinWithTones: "shì", PinyinWithNumericTones: "shi4", Translation: "Ser/Estar", DifficultyLevel: 3},
		{Character: "这", PinyinWithoutTones: "zhe", PinyinWithTones: "zhè", PinyinWithNumericTones: "zhe4", Translation: "Este/Esta", DifficultyLevel: 3},
		{Character: "王", PinyinWithoutTones: "wang", PinyinWithTones: "wáng", PinyinWithNumericTones: "wang2", Translation: "Rei / Sobrenome", DifficultyLevel: 3},
		{Character: "小姐", PinyinWithoutTones: "xiao jie", PinyinWithTones: "xiǎo jiě", PinyinWithNumericTones: "xiao3 jie3", Translation: "Senhorita", DifficultyLevel: 3},
		{Character: "先生", PinyinWithoutTones: "xian sheng", PinyinWithTones: "xiān shēng", PinyinWithNumericTones: "xian1 sheng1", Translation: "Senhor", DifficultyLevel: 3},
		{Character: "太太", PinyinWithoutTones: "tai tai", PinyinWithTones: "tài tai", PinyinWithNumericTones: "tai4 tai5", Translation: "Senhora", DifficultyLevel: 3},
		{Character: "说", PinyinWithoutTones: "shuo", PinyinWithTones: "shuō", PinyinWithNumericTones: "shuo1", Translation: "Falar", DifficultyLevel: 3},
		{Character: "汉语", PinyinWithoutTones: "han yu", PinyinWithTones: "hàn yǔ", PinyinWithNumericTones: "han4 yu3", Translation: "Língua Chinesa", DifficultyLevel: 3},
		{Character: "对不起", PinyinWithoutTones: "dui bu qi", PinyinWithTones: "duì bu qǐ", PinyinWithNumericTones: "dui4 bu4 qi3", Translation: "Desculpe", DifficultyLevel: 3},
		{Character: "没关系", PinyinWithoutTones: "mei guan xi", PinyinWithTones: "méi guān xi", PinyinWithNumericTones: "mei2 guan1 xi5", Translation: "Não tem problema", DifficultyLevel: 3},
		{Character: "的", PinyinWithoutTones: "de", PinyinWithTones: "de", PinyinWithNumericTones: "de5", Translation: "De (posse)", DifficultyLevel: 3},
		{Character: "我的", PinyinWithoutTones: "wo de", PinyinWithTones: "wǒ de", PinyinWithNumericTones: "wo3 de5", Translation: "Meu", DifficultyLevel: 3},
		{Character: "你的", PinyinWithoutTones: "ni de", PinyinWithTones: "nǐ de", PinyinWithNumericTones: "ni3 de5", Translation: "Seu", DifficultyLevel: 3},
		{Character: "会", PinyinWithoutTones: "hui", PinyinWithTones: "huì", PinyinWithNumericTones: "hui4", Translation: "Saber/Poder", DifficultyLevel: 3},
		{Character: "李", PinyinWithoutTones: "li", PinyinWithTones: "lǐ", PinyinWithNumericTones: "li3", Translation: "Ameixa / Sobrenome", DifficultyLevel: 3},
		{Character: "累", PinyinWithoutTones: "lei", PinyinWithTones: "lèi", PinyinWithNumericTones: "lei4", Translation: "Cansado", DifficultyLevel: 4},
		{Character: "呢", PinyinWithoutTones: "ne", PinyinWithTones: "ne", PinyinWithNumericTones: "ne5", Translation: "Partícula", DifficultyLevel: 4},
		{Character: "渴", PinyinWithoutTones: "ke", PinyinWithTones: "kě", PinyinWithNumericTones: "ke3", Translation: "Com sede", DifficultyLevel: 4},
		{Character: "饿", PinyinWithoutTones: "e", PinyinWithTones: "è", PinyinWithNumericTones: "e4", Translation: "Com fome", DifficultyLevel: 4},
		{Character: "困", PinyinWithoutTones: "kun", PinyinWithTones: "kùn", PinyinWithNumericTones: "kun4", Translation: "Com sono", DifficultyLevel: 4},
		{Character: "有一点儿", PinyinWithoutTones: "you yi dian er", PinyinWithTones: "yǒu yī diǎn ér", PinyinWithNumericTones: "you3 yi1 dian3 er2", Translation: "Um pouco", DifficultyLevel: 4},
		{Character: "极了", PinyinWithoutTones: "ji le", PinyinWithTones: "jí le", PinyinWithNumericTones: "ji2 le5", Translation: "Extremamente", DifficultyLevel: 4},
		{Character: "也", PinyinWithoutTones: "ye", PinyinWithTones: "yě", PinyinWithNumericTones: "ye3", Translation: "Também", DifficultyLevel: 4},
		{Character: "都", PinyinWithoutTones: "dou", PinyinWithTones: "dōu", PinyinWithNumericTones: "dou1", Translation: "Todos", DifficultyLevel: 4},
		{Character: "漂亮", PinyinWithoutTones: "piao liang", PinyinWithTones: "piào liang", PinyinWithNumericTones: "piao4 liang5", Translation: "Bonito", DifficultyLevel: 4},
		{Character: "好看", PinyinWithoutTones: "hao kan", PinyinWithTones: "hǎo kàn", PinyinWithNumericTones: "hao3 kan4", Translation: "Bonito", DifficultyLevel: 4},
		{Character: "丑", PinyinWithoutTones: "chou", PinyinWithTones: "chǒu", PinyinWithNumericTones: "chou3", Translation: "Feio", DifficultyLevel: 4},
		{Character: "他", PinyinWithoutTones: "ta", PinyinWithTones: "tā", PinyinWithNumericTones: "ta1", Translation: "Ele", DifficultyLevel: 5},
		{Character: "她", PinyinWithoutTones: "ta", PinyinWithTones: "tā", PinyinWithNumericTones: "ta1", Translation: "Ela", DifficultyLevel: 5},
		{Character: "学习", PinyinWithoutTones: "xue xi", PinyinWithTones: "xué xí", PinyinWithNumericTones: "xue2 xi2", Translation: "Estudar", DifficultyLevel: 5},
		{Character: "什么", PinyinWithoutTones: "shen me", PinyinWithTones: "shén me", PinyinWithNumericTones: "shen2 me5", Translation: "O que", DifficultyLevel: 5},
		{Character: "葡语", PinyinWithoutTones: "pu yu", PinyinWithTones: "pú yǔ", PinyinWithNumericTones: "pu2 yu3", Translation: "Português", DifficultyLevel: 5},
		{Character: "难", PinyinWithoutTones: "nan", PinyinWithTones: "nán", PinyinWithNumericTones: "nan2", Translation: "Difícil", DifficultyLevel: 5},
		{Character: "容易", PinyinWithoutTones: "rong yi", PinyinWithTones: "róng yì", PinyinWithNumericTones: "rong2 yi4", Translation: "Fácil", DifficultyLevel: 5},
		{Character: "圆珠笔", PinyinWithoutTones: "yuan zhu bi", PinyinWithTones: "yuán zhū bǐ", PinyinWithNumericTones: "yuan2 zhu1 bi3", Translation: "Caneta esferográfica", DifficultyLevel: 11},
		{Character: "毛笔", PinyinWithoutTones: "mao bi", PinyinWithTones: "máo bǐ", PinyinWithNumericTones: "mao2 bi3", Translation: "Pincel", DifficultyLevel: 11},
		{Character: "支", PinyinWithoutTones: "zhi", PinyinWithTones: "zhī", PinyinWithNumericTones: "zhi1", Translation: "Classificador (canetas)", DifficultyLevel: 11},
		{Character: "谁", PinyinWithoutTones: "shui", PinyinWithTones: "shuí", PinyinWithNumericTones: "shui2", Translation: "Quem", DifficultyLevel: 11},
		{Character: "李明", PinyinWithoutTones: "li ming", PinyinWithTones: "lǐ míng", PinyinWithNumericTones: "li3 ming2", Translation: "Li Ming", DifficultyLevel: 11},
		{Character: "朋友", PinyinWithoutTones: "peng you", PinyinWithTones: "péng you", PinyinWithNumericTones: "peng2 you5", Translation: "Amigo", DifficultyLevel: 11},
		{Character: "王丽", PinyinWithoutTones: "wang li", PinyinWithTones: "wáng lì", PinyinWithNumericTones: "wang2 li4", Translation: "Wang Li", DifficultyLevel: 11},
		{Character: "找", PinyinWithoutTones: "zhao", PinyinWithTones: "zhǎo", PinyinWithNumericTones: "zhao3", Translation: "Procurar", DifficultyLevel: 11},
		{Character: "男", PinyinWithoutTones: "nan", PinyinWithTones: "nán", PinyinWithNumericTones: "nan2", Translation: "Homem", DifficultyLevel: 11},
		{Character: "女", PinyinWithoutTones: "nv", PinyinWithTones: "nǚ", PinyinWithNumericTones: "nv3", Translation: "Mulher", DifficultyLevel: 11},
		{Character: "谁的", PinyinWithoutTones: "shui de", PinyinWithTones: "shuí de", PinyinWithNumericTones: "shui2 de5", Translation: "De quem", DifficultyLevel: 11},
		{Character: "电影", PinyinWithoutTones: "dian ying", PinyinWithTones: "diàn yǐng", PinyinWithNumericTones: "dian4 ying3", Translation: "Filme", DifficultyLevel: 11},
		{Character: "和一起", PinyinWithoutTones: "he yi qi", PinyinWithTones: "hé yí qǐ", PinyinWithNumericTones: "he2 yi4 qi3", Translation: "Junto com", DifficultyLevel: 11},
		{Character: "同学", PinyinWithoutTones: "tong xue", PinyinWithTones: "tóng xué", PinyinWithNumericTones: "tong2 xue2", Translation: "Colega de classe", DifficultyLevel: 11},
		{Character: "女儿", PinyinWithoutTones: "nv er", PinyinWithTones: "nǚ ér", PinyinWithNumericTones: "nv3 er2", Translation: "Filha", DifficultyLevel: 11},
		{Character: "儿子", PinyinWithoutTones: "er zi", PinyinWithTones: "ér zi", PinyinWithNumericTones: "er2 zi5", Translation: "Filho", DifficultyLevel: 11},
		{Character: "孩子", PinyinWithoutTones: "hai zi", PinyinWithTones: "hái zi", PinyinWithNumericTones: "hai2 zi5", Translation: "Criança", DifficultyLevel: 11},
		{Character: "本", PinyinWithoutTones: "ben", PinyinWithTones: "běn", PinyinWithNumericTones: "ben3", Translation: "Classificador (livros)", DifficultyLevel: 11},
		{Character: "杂志", PinyinWithoutTones: "za zhi", PinyinWithTones: "zá zhì", PinyinWithNumericTones: "za2 zhi4", Translation: "Revista", DifficultyLevel: 11},
		{Character: "张", PinyinWithoutTones: "zhang", PinyinWithTones: "zhāng", PinyinWithNumericTones: "zhang1", Translation: "Classificador (papel)", DifficultyLevel: 11},
		{Character: "纸", PinyinWithoutTones: "zhi", PinyinWithTones: "zhǐ", PinyinWithNumericTones: "zhi3", Translation: "Papel", DifficultyLevel: 11},
		{Character: "报纸", PinyinWithoutTones: "bao zhi", PinyinWithTones: "bào zhǐ", PinyinWithNumericTones: "bao4 zhi3", Translation: "Jornal", DifficultyLevel: 11},
		{Character: "地图", PinyinWithoutTones: "di tu", PinyinWithTones: "dì tú", PinyinWithNumericTones: "di4 tu2", Translation: "Mapa", DifficultyLevel: 11},
		{Character: "画", PinyinWithoutTones: "hua", PinyinWithTones: "huà", PinyinWithNumericTones: "hua4", Translation: "Desenho / Pintar", DifficultyLevel: 11},
		{Character: "桌子", PinyinWithoutTones: "zhuo zi", PinyinWithTones: "zhuō zi", PinyinWithNumericTones: "zhuo1 zi5", Translation: "Mesa", DifficultyLevel: 11},
		{Character: "床", PinyinWithoutTones: "chuang", PinyinWithTones: "chuáng", PinyinWithNumericTones: "chuang2", Translation: "Cama", DifficultyLevel: 11},
		{Character: "笔", PinyinWithoutTones: "bi", PinyinWithTones: "bǐ", PinyinWithNumericTones: "bi3", Translation: "Caneta", DifficultyLevel: 11},
		{Character: "铅笔", PinyinWithoutTones: "qian bi", PinyinWithTones: "qiān bǐ", PinyinWithNumericTones: "qian1 bi3", Translation: "Lápis", DifficultyLevel: 11},
		{Character: "钢笔", PinyinWithoutTones: "gang bi", PinyinWithTones: "gāng bǐ", PinyinWithNumericTones: "gang1 bi3", Translation: "Caneta-tinteiro", DifficultyLevel: 11},
		{Character: "钱", PinyinWithoutTones: "qian", PinyinWithTones: "qián", PinyinWithNumericTones: "qian2", Translation: "Dinheiro", DifficultyLevel: 12},
		{Character: "块", PinyinWithoutTones: "kuai", PinyinWithTones: "kuài", PinyinWithNumericTones: "kuai4", Translation: "Classificador (dinheiro)", DifficultyLevel: 12},
		{Character: "元", PinyinWithoutTones: "yuan", PinyinWithTones: "yuán", PinyinWithNumericTones: "yuan2", Translation: "Yuan", DifficultyLevel: 12},
		{Character: "毛", PinyinWithoutTones: "mao", PinyinWithTones: "máo", PinyinWithNumericTones: "mao2", Translation: "Mao (centavo)", DifficultyLevel: 12},
		{Character: "角", PinyinWithoutTones: "jiao", PinyinWithTones: "jiǎo", PinyinWithNumericTones: "jiao3", Translation: "Jiao (centavo)", DifficultyLevel: 12},
		{Character: "分", PinyinWithoutTones: "fen", PinyinWithTones: "fēn", PinyinWithNumericTones: "fen1", Translation: "Fen (centavo)", DifficultyLevel: 12},
		{Character: "苹果", PinyinWithoutTones: "ping guo", PinyinWithTones: "píng guǒ", PinyinWithNumericTones: "ping2 guo3", Translation: "Maçã", DifficultyLevel: 12},
		{Character: "瓶", PinyinWithoutTones: "ping", PinyinWithTones: "píng", PinyinWithNumericTones: "ping2", Translation: "Garrafa", DifficultyLevel: 12},
		{Character: "可口可乐", PinyinWithoutTones: "ke kou ke le", PinyinWithTones: "kě kǒu kě lè", PinyinWithNumericTones: "ke3 kou3 ke3 le4", Translation: "Coca-Cola", DifficultyLevel: 12},
		{Character: "香蕉", PinyinWithoutTones: "xiang jiao", PinyinWithTones: "xiāng jiāo", PinyinWithNumericTones: "xiang1 jiao1", Translation: "Banana", DifficultyLevel: 12},
		{Character: "贵", PinyinWithoutTones: "gui", PinyinWithTones: "guì", PinyinWithNumericTones: "gui4", Translation: "Caro", DifficultyLevel: 12},
		{Character: "便宜", PinyinWithoutTones: "pian yi", PinyinWithTones: "pián yi", PinyinWithNumericTones: "pian2 yi5", Translation: "Barato", DifficultyLevel: 12},
		{Character: "条", PinyinWithoutTones: "tiao", PinyinWithTones: "tiáo", PinyinWithNumericTones: "tiao2", Translation: "Classificador (longos)", DifficultyLevel: 12},
		{Character: "裤子", PinyinWithoutTones: "ku zi", PinyinWithTones: "kù zi", PinyinWithNumericTones: "ku4 zi5", Translation: "Calça", DifficultyLevel: 12},
		{Character: "裙子", PinyinWithoutTones: "qun zi", PinyinWithTones: "qún zi", PinyinWithNumericTones: "qun2 zi5", Translation: "Saia", DifficultyLevel: 12},
		{Character: "一共", PinyinWithoutTones: "yi gong", PinyinWithTones: "yí gòng", PinyinWithNumericTones: "yi2 gong4", Translation: "No total", DifficultyLevel: 12},
		{Character: "一百", PinyinWithoutTones: "yi bai", PinyinWithTones: "yì bǎi", PinyinWithNumericTones: "yi4 bai3", Translation: "Cem", DifficultyLevel: 12},
		{Character: "给", PinyinWithoutTones: "gei", PinyinWithTones: "gěi", PinyinWithNumericTones: "gei3", Translation: "Dar", DifficultyLevel: 12},
		{Character: "葡萄", PinyinWithoutTones: "pu tao", PinyinWithTones: "pú tao", PinyinWithNumericTones: "pu2 tao5", Translation: "Uva", DifficultyLevel: 12},
		{Character: "梨", PinyinWithoutTones: "li", PinyinWithTones: "lí", PinyinWithNumericTones: "li2", Translation: "Pera", DifficultyLevel: 12},
		{Character: "桔子", PinyinWithoutTones: "ju zi", PinyinWithTones: "jú zi", PinyinWithNumericTones: "ju2 zi5", Translation: "Tangerina", DifficultyLevel: 12},
		{Character: "橙子", PinyinWithoutTones: "cheng zi", PinyinWithTones: "chéng zi", PinyinWithNumericTones: "cheng2 zi5", Translation: "Laranja", DifficultyLevel: 12},
		{Character: "西瓜", PinyinWithoutTones: "xi gua", PinyinWithTones: "xī guā", PinyinWithNumericTones: "xi1 gua1", Translation: "Melancia", DifficultyLevel: 12},
		{Character: "牛奶", PinyinWithoutTones: "niu nai", PinyinWithTones: "niú nǎi", PinyinWithNumericTones: "niu2 nai3", Translation: "Leite", DifficultyLevel: 12},
		{Character: "酸奶", PinyinWithoutTones: "suan nai", PinyinWithTones: "suān nǎi", PinyinWithNumericTones: "suan1 nai3", Translation: "Iogurte", DifficultyLevel: 12},
		{Character: "水", PinyinWithoutTones: "shui", PinyinWithTones: "shuǐ", PinyinWithNumericTones: "shui3", Translation: "Água", DifficultyLevel: 12},
		{Character: "啤酒", PinyinWithoutTones: "pi jiu", PinyinWithTones: "pí jiǔ", PinyinWithNumericTones: "pi2 jiu3", Translation: "Cerveja", DifficultyLevel: 12},
		{Character: "饮料", PinyinWithoutTones: "yin liao", PinyinWithTones: "yǐn liào", PinyinWithNumericTones: "yin3 liao4", Translation: "Bebida", DifficultyLevel: 12},
		{Character: "人民币", PinyinWithoutTones: "ren min bi", PinyinWithTones: "rén mín bì", PinyinWithNumericTones: "ren2 min2 bi4", Translation: "Renminbi", DifficultyLevel: 12},
		{Character: "黑奥", PinyinWithoutTones: "hei ao", PinyinWithTones: "hēi ào", PinyinWithNumericTones: "hei1 ao4", Translation: "Real (moeda)", DifficultyLevel: 12},
		{Character: "美元", PinyinWithoutTones: "mei yuan", PinyinWithTones: "měi yuán", PinyinWithNumericTones: "mei3 yuan2", Translation: "Dólar", DifficultyLevel: 12},
		{Character: "欧元", PinyinWithoutTones: "ou yuan", PinyinWithTones: "ōu yuán", PinyinWithNumericTones: "ou1 yuan2", Translation: "Euro", DifficultyLevel: 12},
		{Character: "兑换率", PinyinWithoutTones: "dui huan lv", PinyinWithTones: "duì huàn lǜ", PinyinWithNumericTones: "dui4 huan4 lv4", Translation: "Taxa de câmbio", DifficultyLevel: 12},
		{Character: "打", PinyinWithoutTones: "da", PinyinWithTones: "dǎ", PinyinWithNumericTones: "da3", Translation: "Bater/Jogar", DifficultyLevel: 13},
		{Character: "喝", PinyinWithoutTones: "he", PinyinWithTones: "hē", PinyinWithNumericTones: "he1", Translation: "Beber", DifficultyLevel: 13},
		{Character: "球", PinyinWithoutTones: "qiu", PinyinWithTones: "qiú", PinyinWithNumericTones: "qiu2", Translation: "Bola", DifficultyLevel: 13},
		{Character: "唱歌", PinyinWithoutTones: "chang ge", PinyinWithTones: "chàng gē", PinyinWithNumericTones: "chang4 ge1", Translation: "Cantar", DifficultyLevel: 13},
		{Character: "信", PinyinWithoutTones: "xin", PinyinWithTones: "xìn", PinyinWithNumericTones: "xin4", Translation: "Carta", DifficultyLevel: 13},
		{Character: "茶", PinyinWithoutTones: "cha", PinyinWithTones: "chá", PinyinWithNumericTones: "cha2", Translation: "Chá", DifficultyLevel: 13},
		{Character: "吃", PinyinWithoutTones: "chi", PinyinWithTones: "chī", PinyinWithNumericTones: "chi1", Translation: "Comer", DifficultyLevel: 13},
		{Character: "饭", PinyinWithoutTones: "fan", PinyinWithTones: "fàn", PinyinWithNumericTones: "fan4", Translation: "Arroz/Comida", DifficultyLevel: 13},
		{Character: "上课", PinyinWithoutTones: "shang ke", PinyinWithTones: "shàng kè", PinyinWithNumericTones: "shang4 ke4", Translation: "Ir para aula", DifficultyLevel: 13},
		{Character: "休息", PinyinWithoutTones: "xiu xi", PinyinWithTones: "xiū xi", PinyinWithNumericTones: "xiu1 xi5", Translation: "Descansar", DifficultyLevel: 13},
		{Character: "作业", PinyinWithoutTones: "zuo ye", PinyinWithTones: "zuò yè", PinyinWithNumericTones: "zuo4 ye4", Translation: "Dever de casa", DifficultyLevel: 13},
		{Character: "睡觉", PinyinWithoutTones: "shui jiao", PinyinWithTones: "shuì jiào", PinyinWithNumericTones: "shui4 jiao4", Translation: "Dormir", DifficultyLevel: 13},
		{Character: "写", PinyinWithoutTones: "xie", PinyinWithTones: "xiě", PinyinWithNumericTones: "xie3", Translation: "Escrever", DifficultyLevel: 13},
		{Character: "听", PinyinWithoutTones: "ting", PinyinWithTones: "tīng", PinyinWithNumericTones: "ting1", Translation: "Ouvir", DifficultyLevel: 13},
		{Character: "做饭", PinyinWithoutTones: "zuo fan", PinyinWithTones: "zuò fàn", PinyinWithNumericTones: "zuo4 fan4", Translation: "Fazer comida", DifficultyLevel: 13},
		{Character: "水果", PinyinWithoutTones: "shui guo", PinyinWithTones: "shuǐ guǒ", PinyinWithNumericTones: "shui3 guo3", Translation: "Fruta", DifficultyLevel: 13},
		{Character: "汉子", PinyinWithoutTones: "han zi", PinyinWithTones: "hàn zì", PinyinWithNumericTones: "han4 zi4", Translation: "Caractere chinês", DifficultyLevel: 13},
		{Character: "洗", PinyinWithoutTones: "xi", PinyinWithTones: "xǐ", PinyinWithNumericTones: "xi3", Translation: "Lavar", DifficultyLevel: 13},
		{Character: "读", PinyinWithoutTones: "du", PinyinWithTones: "dú", PinyinWithNumericTones: "du2", Translation: "Ler", DifficultyLevel: 13},
		{Character: "念", PinyinWithoutTones: "nian", PinyinWithTones: "niàn", PinyinWithNumericTones: "nian4", Translation: "Ler em voz", DifficultyLevel: 13},
		{Character: "课文", PinyinWithoutTones: "ke wen", PinyinWithTones: "kè wén", PinyinWithNumericTones: "ke4 wen2", Translation: "Texto da lição", DifficultyLevel: 13},
		{Character: "音乐", PinyinWithoutTones: "yin yue", PinyinWithTones: "yīn yuè", PinyinWithNumericTones: "yin1 yue4", Translation: "Música", DifficultyLevel: 13},
		{Character: "面包", PinyinWithoutTones: "mian bao", PinyinWithTones: "miàn bāo", PinyinWithNumericTones: "mian4 bao1", Translation: "Pão", DifficultyLevel: 13},
		{Character: "正在", PinyinWithoutTones: "zheng zai", PinyinWithTones: "zhèng zài", PinyinWithNumericTones: "zheng4 zai4", Translation: "Estar (ação contínua)", DifficultyLevel: 13},
		{Character: "衣服", PinyinWithoutTones: "yi fu", PinyinWithTones: "yī fu", PinyinWithNumericTones: "yi1 fu5", Translation: "Roupa", DifficultyLevel: 13},
		{Character: "电话", PinyinWithoutTones: "dian hua", PinyinWithTones: "diàn huà", PinyinWithNumericTones: "dian4 hua4", Translation: "Telefone", DifficultyLevel: 13},
		{Character: "电视", PinyinWithoutTones: "dian shi", PinyinWithTones: "diàn shì", PinyinWithNumericTones: "dian4 shi4", Translation: "Televisão", DifficultyLevel: 13},
		{Character: "牛肉", PinyinWithoutTones: "niu rou", PinyinWithTones: "niú ròu", PinyinWithNumericTones: "niu2 rou4", Translation: "Carne de boi", DifficultyLevel: 13},
		{Character: "鸡肉", PinyinWithoutTones: "ji rou", PinyinWithTones: "jī ròu", PinyinWithNumericTones: "ji1 rou4", Translation: "Carne de frango", DifficultyLevel: 13},
		{Character: "鱼肉", PinyinWithoutTones: "yu rou", PinyinWithTones: "yú ròu", PinyinWithNumericTones: "yu2 rou4", Translation: "Carne de peixe", DifficultyLevel: 13},
		{Character: "虾", PinyinWithoutTones: "xia", PinyinWithTones: "xiā", PinyinWithNumericTones: "xia1", Translation: "Camarão", DifficultyLevel: 13},
		{Character: "羊肉", PinyinWithoutTones: "yang rou", PinyinWithTones: "yáng ròu", PinyinWithNumericTones: "yang2 rou4", Translation: "Carne de carneiro", DifficultyLevel: 13},
		{Character: "猪肉", PinyinWithoutTones: "zhu rou", PinyinWithTones: "zhū ròu", PinyinWithNumericTones: "zhu1 rou4", Translation: "Carne de porco", DifficultyLevel: 13},
		{Character: "怎么", PinyinWithoutTones: "zen me", PinyinWithTones: "zěn me", PinyinWithNumericTones: "zen3 me5", Translation: "Como", DifficultyLevel: 14},
		{Character: "坐", PinyinWithoutTones: "zuo", PinyinWithTones: "zuò", PinyinWithNumericTones: "zuo4", Translation: "Sentar", DifficultyLevel: 14},
		{Character: "公共汽车", PinyinWithoutTones: "gong gong qi che", PinyinWithTones: "gōng gòng qì chē", PinyinWithNumericTones: "gong1 gong4 qi4 che1", Translation: "Ônibus", DifficultyLevel: 14},
		{Character: "医院", PinyinWithoutTones: "yi yuan", PinyinWithTones: "yī yuàn", PinyinWithNumericTones: "yi1 yuan4", Translation: "Hospital", DifficultyLevel: 14},
		{Character: "怎么了", PinyinWithoutTones: "zen me le", PinyinWithTones: "zěn me le", PinyinWithNumericTones: "zen3 me5 le5", Translation: "O que aconteceu?", DifficultyLevel: 14},
		{Character: "舒服", PinyinWithoutTones: "shu fu", PinyinWithTones: "shū fu", PinyinWithNumericTones: "shu1 fu5", Translation: "Confortável", DifficultyLevel: 14},
		{Character: "市中心", PinyinWithoutTones: "shi zhong xin", PinyinWithTones: "shì zhōng xīn", PinyinWithNumericTones: "shi4 zhong1 xin1", Translation: "Centro", DifficultyLevel: 14},
		{Character: "走", PinyinWithoutTones: "zou", PinyinWithTones: "zǒu", PinyinWithNumericTones: "zou3", Translation: "Andar", DifficultyLevel: 14},
		{Character: "地铁", PinyinWithoutTones: "di tie", PinyinWithTones: "dì tiě", PinyinWithNumericTones: "di4 tie3", Translation: "Metrô", DifficultyLevel: 14},
		{Character: "病", PinyinWithoutTones: "bing", PinyinWithTones: "bìng", PinyinWithNumericTones: "bing4", Translation: "Ficar doente", DifficultyLevel: 14},
		{Character: "胃口", PinyinWithoutTones: "wei kou", PinyinWithTones: "wèi kǒu", PinyinWithNumericTones: "wei4 kou3", Translation: "Apetite", DifficultyLevel: 14},
		{Character: "飞机", PinyinWithoutTones: "fei ji", PinyinWithTones: "fēi jī", PinyinWithNumericTones: "fei1 ji1", Translation: "Avião", DifficultyLevel: 14},
		{Character: "出租车", PinyinWithoutTones: "chu zu che", PinyinWithTones: "chū zú chē", PinyinWithNumericTones: "chu1 zu2 che1", Translation: "Táxi", DifficultyLevel: 14},
		{Character: "开车", PinyinWithoutTones: "kai che", PinyinWithTones: "kāi chē", PinyinWithNumericTones: "kai1 che1", Translation: "Dirigir", DifficultyLevel: 14},
		{Character: "火车", PinyinWithoutTones: "huo che", PinyinWithTones: "huǒ chē", PinyinWithNumericTones: "huo3 che1", Translation: "Trem", DifficultyLevel: 14},
		{Character: "船", PinyinWithoutTones: "chuan", PinyinWithTones: "chuán", PinyinWithNumericTones: "chuan2", Translation: "Barco", DifficultyLevel: 14},
		{Character: "骑", PinyinWithoutTones: "qi", PinyinWithTones: "qí", PinyinWithNumericTones: "qi2", Translation: "Andar de", DifficultyLevel: 14},
		{Character: "自信车", PinyinWithoutTones: "zi xing che", PinyinWithTones: "zì xíng chē", PinyinWithNumericTones: "zi4 xing2 che1", Translation: "Bicicleta", DifficultyLevel: 14},
		{Character: "走路", PinyinWithoutTones: "zou lu", PinyinWithTones: "zǒu lù", PinyinWithNumericTones: "zou3 lu4", Translation: "Caminhar", DifficultyLevel: 14},
		{Character: "海滨", PinyinWithoutTones: "hai bin", PinyinWithTones: "hǎi bīn", PinyinWithNumericTones: "hai3 bin1", Translation: "Praia", DifficultyLevel: 14},
		{Character: "北京", PinyinWithoutTones: "bei jing", PinyinWithTones: "běi jīng", PinyinWithNumericTones: "bei3 jing1", Translation: "Pequim", DifficultyLevel: 14},
		{Character: "香港", PinyinWithoutTones: "xiang gang", PinyinWithTones: "xiāng gǎng", PinyinWithNumericTones: "xiang1 gang3", Translation: "Hong Kong", DifficultyLevel: 14},
		{Character: "天安门广场", PinyinWithoutTones: "tian an men guang chang", PinyinWithTones: "tiān ān mén guǎng chǎng", PinyinWithNumericTones: "tian1 an1 men2 guang3 chang3", Translation: "Praça da Paz Celestial", DifficultyLevel: 14},
		{Character: "发烧", PinyinWithoutTones: "fa shao", PinyinWithTones: "fā shāo", PinyinWithNumericTones: "fa1 shao1", Translation: "Ter febre", DifficultyLevel: 14},
		{Character: "感冒", PinyinWithoutTones: "gan mao", PinyinWithTones: "gǎn mào", PinyinWithNumericTones: "gan3 mao4", Translation: "Resfriado", DifficultyLevel: 14},
		{Character: "疼", PinyinWithoutTones: "teng", PinyinWithTones: "téng", PinyinWithNumericTones: "teng2", Translation: "Doer", DifficultyLevel: 14},
		{Character: "头", PinyinWithoutTones: "tou", PinyinWithTones: "tóu", PinyinWithNumericTones: "tou2", Translation: "Cabeça", DifficultyLevel: 14},
		{Character: "牙", PinyinWithoutTones: "ya", PinyinWithTones: "yá", PinyinWithNumericTones: "ya2", Translation: "Dente", DifficultyLevel: 14},
		{Character: "肚子", PinyinWithoutTones: "du zi", PinyinWithTones: "dù zi", PinyinWithNumericTones: "du4 zi5", Translation: "Barriga", DifficultyLevel: 14},
		{Character: "咳嗽", PinyinWithoutTones: "ke sou", PinyinWithTones: "ké sou", PinyinWithNumericTones: "ke2 sou5", Translation: "Tossir", DifficultyLevel: 14},
		{Character: "奶奶", PinyinWithoutTones: "nai nai", PinyinWithTones: "nǎi nai", PinyinWithNumericTones: "nai3 nai5", Translation: "Avó", DifficultyLevel: 14},
		{Character: "爷爷", PinyinWithoutTones: "ye ye", PinyinWithTones: "yé ye", PinyinWithNumericTones: "ye2 ye5", Translation: "Avô", DifficultyLevel: 14},
		{Character: "叔叔", PinyinWithoutTones: "shu shu", PinyinWithTones: "shū shu", PinyinWithNumericTones: "shu1 shu5", Translation: "Tio", DifficultyLevel: 14},
		{Character: "阿姨", PinyinWithoutTones: "a yi", PinyinWithTones: "ā yí", PinyinWithNumericTones: "a1 yi2", Translation: "Tia", DifficultyLevel: 14},
		{Character: "怎么样", PinyinWithoutTones: "zen me yang", PinyinWithTones: "zěn me yàng", PinyinWithNumericTones: "zen3 me5 yang4", Translation: "Como é?", DifficultyLevel: 15},
		{Character: "天气", PinyinWithoutTones: "tian qi", PinyinWithTones: "tiān qì", PinyinWithNumericTones: "tian1 qi4", Translation: "Tempo", DifficultyLevel: 15},
		{Character: "不错", PinyinWithoutTones: "bu cuo", PinyinWithTones: "bú cuò", PinyinWithNumericTones: "bu2 cuo4", Translation: "Nada mau", DifficultyLevel: 15},
		{Character: "冷", PinyinWithoutTones: "leng", PinyinWithTones: "lěng", PinyinWithNumericTones: "leng3", Translation: "Frio", DifficultyLevel: 15},
		{Character: "热", PinyinWithoutTones: "re", PinyinWithTones: "rè", PinyinWithNumericTones: "re4", Translation: "Quente", DifficultyLevel: 15},
		{Character: "周末", PinyinWithoutTones: "zhou mo", PinyinWithTones: "zhōu mò", PinyinWithNumericTones: "zhou1 mo4", Translation: "Fim de semana", DifficultyLevel: 15},
		{Character: "过", PinyinWithoutTones: "guo", PinyinWithTones: "guò", PinyinWithNumericTones: "guo4", Translation: "Passar", DifficultyLevel: 15},
		{Character: "得", PinyinWithoutTones: "de", PinyinWithTones: "de", PinyinWithNumericTones: "de5", Translation: "Partícula", DifficultyLevel: 15},
		{Character: "行", PinyinWithoutTones: "xing", PinyinWithTones: "xíng", PinyinWithNumericTones: "xing2", Translation: "Tudo bem", DifficultyLevel: 15},
		{Character: "还", PinyinWithoutTones: "hai", PinyinWithTones: "hái", PinyinWithNumericTones: "hai2", Translation: "Ainda", DifficultyLevel: 15},
		{Character: "时间", PinyinWithoutTones: "shi jian", PinyinWithTones: "shí jiān", PinyinWithNumericTones: "shi2 jian1", Translation: "Tempo (duração)", DifficultyLevel: 15},
		{Character: "卖", PinyinWithoutTones: "mai", PinyinWithTones: "mài", PinyinWithNumericTones: "mai4", Translation: "Vender", DifficultyLevel: 15},
		{Character: "买", PinyinWithoutTones: "mai", PinyinWithTones: "mǎi", PinyinWithNumericTones: "mai3", Translation: "Comprar", DifficultyLevel: 15},
		{Character: "度", PinyinWithoutTones: "du", PinyinWithTones: "dù", PinyinWithNumericTones: "du4", Translation: "Grau", DifficultyLevel: 15},
		{Character: "太阳", PinyinWithoutTones: "tai yang", PinyinWithTones: "tài yáng", PinyinWithNumericTones: "tai4 yang2", Translation: "Sol", DifficultyLevel: 15},
		{Character: "刮风", PinyinWithoutTones: "gua feng", PinyinWithTones: "guā fēng", PinyinWithNumericTones: "gua1 feng1", Translation: "Ventar", DifficultyLevel: 15},
		{Character: "下雨", PinyinWithoutTones: "xia yu", PinyinWithTones: "xià yǔ", PinyinWithNumericTones: "xia4 yu3", Translation: "Chover", DifficultyLevel: 15},
		{Character: "闷热", PinyinWithoutTones: "men re", PinyinWithTones: "mēn rè", PinyinWithNumericTones: "men1 re4", Translation: "Abafado", DifficultyLevel: 15},
		{Character: "旅行", PinyinWithoutTones: "lv xing", PinyinWithTones: "lǚ xíng", PinyinWithNumericTones: "lv3 xing2", Translation: "Viajar", DifficultyLevel: 15},
		{Character: "散步", PinyinWithoutTones: "san bu", PinyinWithTones: "sàn bù", PinyinWithNumericTones: "san4 bu4", Translation: "Passear", DifficultyLevel: 15},
		{Character: "还可以", PinyinWithoutTones: "hai ke yi", PinyinWithTones: "hái kě yǐ", PinyinWithNumericTones: "hai2 ke3 yi3", Translation: "Mais ou menos", DifficultyLevel: 15},
		{Character: "马马虎虎", PinyinWithoutTones: "ma ma hu hu", PinyinWithTones: "mǎ ma hū hū", PinyinWithNumericTones: "ma3 ma5 hu1 hu5", Translation: "Mais ou menos", DifficultyLevel: 15},
		{Character: "德语", PinyinWithoutTones: "de yu", PinyinWithTones: "dé yǔ", PinyinWithNumericTones: "de2 yu3", Translation: "Alemão", DifficultyLevel: 15},
		{Character: "法语", PinyinWithoutTones: "fa yu", PinyinWithTones: "fǎ yǔ", PinyinWithNumericTones: "fa3 yu3", Translation: "Francês", DifficultyLevel: 15},
		{Character: "西班牙语", PinyinWithoutTones: "xi ban ya yu", PinyinWithTones: "xī bān yá yǔ", PinyinWithNumericTones: "xi1 ban1 ya1 yu3", Translation: "Espanhol", DifficultyLevel: 15},
		{Character: "电视机", PinyinWithoutTones: "dian shi ji", PinyinWithTones: "diàn shì jī", PinyinWithNumericTones: "dian4 shi4 ji1", Translation: "Aparelho de TV", DifficultyLevel: 15},
		{Character: "电冰箱", PinyinWithoutTones: "dian bing xiang", PinyinWithTones: "diàn bīng xiāng", PinyinWithNumericTones: "dian4 bing1 xiang1", Translation: "Geladeira", DifficultyLevel: 15},
		{Character: "电风扇", PinyinWithoutTones: "dian feng shan", PinyinWithTones: "diàn fēng shàn", PinyinWithNumericTones: "dian4 feng1 shan4", Translation: "Ventilador", DifficultyLevel: 15},
		{Character: "冷气机", PinyinWithoutTones: "leng qi ji", PinyinWithTones: "lěng qì jī", PinyinWithNumericTones: "leng3 qi4 ji1", Translation: "Ar condicionado", DifficultyLevel: 15},
		{Character: "一千", PinyinWithoutTones: "yi qian", PinyinWithTones: "yì qiān", PinyinWithNumericTones: "yi4 qian1", Translation: "Mil", DifficultyLevel: 15},
		{Character: "电脑", PinyinWithoutTones: "dian nao", PinyinWithTones: "diàn nǎo", PinyinWithNumericTones: "dian4 nao3", Translation: "Computador", DifficultyLevel: 15},
		{Character: "洗衣机", PinyinWithoutTones: "xi yi ji", PinyinWithTones: "xǐ yī jī", PinyinWithNumericTones: "xi3 yi1 ji1", Translation: "Máquina de lavar", DifficultyLevel: 15},
		{Character: "微波炉", PinyinWithoutTones: "wei bo lu", PinyinWithTones: "wēi bō lú", PinyinWithNumericTones: "wei1 bo1 lu2", Translation: "Microondas", DifficultyLevel: 15},
		{Character: "录像机", PinyinWithoutTones: "lu xiang ji", PinyinWithTones: "lù xiàng jī", PinyinWithNumericTones: "lu4 xiang4 ji1", Translation: "Gravador de vídeo", DifficultyLevel: 15},
		{Character: "录音机", PinyinWithoutTones: "lu yin ji", PinyinWithTones: "lù yīn jī", PinyinWithNumericTones: "lu4 yin1 ji1", Translation: "Gravador de áudio", DifficultyLevel: 15},
		{Character: "随身听", PinyinWithoutTones: "sui shen ting", PinyinWithTones: "suí shēn tīng", PinyinWithNumericTones: "sui2 shen1 ting1", Translation: "Walkman", DifficultyLevel: 15},
		{Character: "什么时侯", PinyinWithoutTones: "shen me shi hou", PinyinWithTones: "shén me shí hou", PinyinWithNumericTones: "shen2 me5 shi2 hou5", Translation: "Quando", DifficultyLevel: 16},
		{Character: "上课", PinyinWithoutTones: "shang ke", PinyinWithTones: "shàng kè", PinyinWithNumericTones: "shang4 ke4", Translation: "Começar aula", DifficultyLevel: 16},
		{Character: "上午", PinyinWithoutTones: "shang wu", PinyinWithTones: "shàng wǔ", PinyinWithNumericTones: "shang4 wu3", Translation: "Manhã", DifficultyLevel: 16},
		{Character: "下午", PinyinWithoutTones: "xia wu", PinyinWithTones: "xià wǔ", PinyinWithNumericTones: "xia4 wu3", Translation: "Tarde", DifficultyLevel: 16},
		{Character: "回来", PinyinWithoutTones: "hui lai", PinyinWithTones: "huí lái", PinyinWithNumericTones: "hui2 lai2", Translation: "Voltar", DifficultyLevel: 16},
		{Character: "有空儿", PinyinWithoutTones: "you kong er", PinyinWithTones: "yǒu kòng ér", PinyinWithNumericTones: "you3 kong4 er2", Translation: "Ter tempo", DifficultyLevel: 16},
		{Character: "晚上", PinyinWithoutTones: "wan shang", PinyinWithTones: "wǎn shang", PinyinWithNumericTones: "wan3 shang5", Translation: "Noite", DifficultyLevel: 16},
		{Character: "事", PinyinWithoutTones: "shi", PinyinWithTones: "shì", PinyinWithNumericTones: "shi4", Translation: "Assunto", DifficultyLevel: 16},
		{Character: "结婚", PinyinWithoutTones: "jie hun", PinyinWithTones: "jié hūn", PinyinWithNumericTones: "jie2 hun1", Translation: "Casar", DifficultyLevel: 16},
		{Character: "以后", PinyinWithoutTones: "yi hou", PinyinWithTones: "yǐ hòu", PinyinWithNumericTones: "yi3 hou4", Translation: "Depois", DifficultyLevel: 16},
		{Character: "以前", PinyinWithoutTones: "yi qian", PinyinWithTones: "yǐ qián", PinyinWithNumericTones: "yi3 qian2", Translation: "Antes", DifficultyLevel: 16},
		{Character: "小时", PinyinWithoutTones: "xiao shi", PinyinWithTones: "xiǎo shí", PinyinWithNumericTones: "xiao3 shi2", Translation: "Hora", DifficultyLevel: 16},
		{Character: "认识", PinyinWithoutTones: "ren shi", PinyinWithTones: "rèn shi", PinyinWithNumericTones: "ren4 shi5", Translation: "Conhecer", DifficultyLevel: 16},
		{Character: "有人", PinyinWithoutTones: "you ren", PinyinWithTones: "yǒu rén", PinyinWithNumericTones: "you3 ren2", Translation: "Alguém", DifficultyLevel: 16},
		{Character: "刚才", PinyinWithoutTones: "gang cai", PinyinWithTones: "gāng cái", PinyinWithNumericTones: "gang1 cai2", Translation: "Agora pouco", DifficultyLevel: 16},
		{Character: "手机", PinyinWithoutTones: "shou ji", PinyinWithTones: "shǒu jī", PinyinWithNumericTones: "shou3 ji1", Translation: "Celular", DifficultyLevel: 16},
		{Character: "号码", PinyinWithoutTones: "hao ma", PinyinWithTones: "hào mǎ", PinyinWithNumericTones: "hao4 ma3", Translation: "Número", DifficultyLevel: 16},
		{Character: "上学", PinyinWithoutTones: "shang xue", PinyinWithTones: "shàng xué", PinyinWithNumericTones: "shang4 xue2", Translation: "Ir escola", DifficultyLevel: 16},
		{Character: "上班", PinyinWithoutTones: "shang ban", PinyinWithTones: "shàng bān", PinyinWithNumericTones: "shang4 ban1", Translation: "Ir trabalho", DifficultyLevel: 16},
		{Character: "上街", PinyinWithoutTones: "shang jie", PinyinWithTones: "shàng jiē", PinyinWithNumericTones: "shang4 jie1", Translation: "Ir à rua", DifficultyLevel: 16},
		{Character: "起床", PinyinWithoutTones: "qi chuang", PinyinWithTones: "qǐ chuáng", PinyinWithNumericTones: "qi3 chuang2", Translation: "Levantar", DifficultyLevel: 16},
		{Character: "早上", PinyinWithoutTones: "zao shang", PinyinWithTones: "zǎo shang", PinyinWithNumericTones: "zao3 shang5", Translation: "De manhã", DifficultyLevel: 16},
		{Character: "毕业", PinyinWithoutTones: "bi ye", PinyinWithTones: "bì yè", PinyinWithNumericTones: "bi4 ye4", Translation: "Formar", DifficultyLevel: 16},
		{Character: "银行", PinyinWithoutTones: "yin hang", PinyinWithTones: "yín háng", PinyinWithNumericTones: "yin2 hang2", Translation: "Banco", DifficultyLevel: 16},
		{Character: "分", PinyinWithoutTones: "fen", PinyinWithTones: "fēn", PinyinWithNumericTones: "fen1", Translation: "Minuto", DifficultyLevel: 16},
		{Character: "步行", PinyinWithoutTones: "bu xing", PinyinWithTones: "bù xíng", PinyinWithNumericTones: "bu4 xing2", Translation: "Andar", DifficultyLevel: 16},
		{Character: "上海", PinyinWithoutTones: "shang hai", PinyinWithTones: "shàng hǎi", PinyinWithNumericTones: "shang4 hai3", Translation: "Xangai", DifficultyLevel: 16},
		{Character: "前年", PinyinWithoutTones: "qian nian", PinyinWithTones: "qián nián", PinyinWithNumericTones: "qian2 nian2", Translation: "Ano retrasado", DifficultyLevel: 16},
		{Character: "邮局", PinyinWithoutTones: "you ju", PinyinWithTones: "yóu jú", PinyinWithNumericTones: "you2 ju2", Translation: "Correios", DifficultyLevel: 16},
		{Character: "办公室", PinyinWithoutTones: "ban gong shi", PinyinWithTones: "bàn gōng shì", PinyinWithNumericTones: "ban4 gong1 shi4", Translation: "Escritório", DifficultyLevel: 16},
		{Character: "为", PinyinWithoutTones: "wei", PinyinWithTones: "wèi", PinyinWithNumericTones: "wei4", Translation: "Para", DifficultyLevel: 18},
		{Character: "为什么", PinyinWithoutTones: "wei shen me", PinyinWithTones: "wèi shén me", PinyinWithNumericTones: "wei4 shen2 me5", Translation: "Por que", DifficultyLevel: 18},
		{Character: "高兴", PinyinWithoutTones: "gao xing", PinyinWithTones: "gāo xìng", PinyinWithNumericTones: "gao1 xing4", Translation: "Feliz", DifficultyLevel: 18},
		{Character: "总是", PinyinWithoutTones: "zong shi", PinyinWithTones: "zǒng shì", PinyinWithNumericTones: "zong3 shi4", Translation: "Sempre", DifficultyLevel: 18},
		{Character: "迟到", PinyinWithoutTones: "chi dao", PinyinWithTones: "chí dào", PinyinWithNumericTones: "chi2 dao4", Translation: "Atrasar", DifficultyLevel: 18},
		{Character: "因为", PinyinWithoutTones: "yin wei", PinyinWithTones: "yīn wèi", PinyinWithNumericTones: "yin1 wei4", Translation: "Porque", DifficultyLevel: 18},
		{Character: "所以", PinyinWithoutTones: "suo yi", PinyinWithTones: "suǒ yǐ", PinyinWithNumericTones: "suo3 yi3", Translation: "Por isso", DifficultyLevel: 18},
		{Character: "忘", PinyinWithoutTones: "wang", PinyinWithTones: "wàng", PinyinWithNumericTones: "wang4", Translation: "Esquecer", DifficultyLevel: 18},
		{Character: "告诉", PinyinWithoutTones: "gao su", PinyinWithTones: "gào su", PinyinWithNumericTones: "gao4 su5", Translation: "Contar", DifficultyLevel: 18},
		{Character: "爱", PinyinWithoutTones: "ai", PinyinWithTones: "ài", PinyinWithNumericTones: "ai4", Translation: "Amar", DifficultyLevel: 18},
		{Character: "爱人", PinyinWithoutTones: "ai ren", PinyinWithTones: "ài ren", PinyinWithNumericTones: "ai4 ren5", Translation: "Esposo", DifficultyLevel: 18},
		{Character: "消息", PinyinWithoutTones: "xiao xi", PinyinWithTones: "xiāo xi", PinyinWithNumericTones: "xiao1 xi5", Translation: "Notícia", DifficultyLevel: 18},
		{Character: "怕", PinyinWithoutTones: "pa", PinyinWithTones: "pà", PinyinWithNumericTones: "pa4", Translation: "Medo", DifficultyLevel: 18},
		{Character: "生气", PinyinWithoutTones: "sheng qi", PinyinWithTones: "shēng qì", PinyinWithNumericTones: "sheng1 qi4", Translation: "Raiva", DifficultyLevel: 18},
		{Character: "急事", PinyinWithoutTones: "ji shi", PinyinWithTones: "jí shì", PinyinWithNumericTones: "ji2 shi4", Translation: "Urgência", DifficultyLevel: 18},
		{Character: "咖啡", PinyinWithoutTones: "ka fei", PinyinWithTones: "kā fēi", PinyinWithNumericTones: "ka1 fei1", Translation: "Café", DifficultyLevel: 18},
		{Character: "或者", PinyinWithoutTones: "huo zhe", PinyinWithTones: "huò zhě", PinyinWithNumericTones: "huo4 zhe3", Translation: "Ou", DifficultyLevel: 18},
		{Character: "哭", PinyinWithoutTones: "ku", PinyinWithTones: "kū", PinyinWithNumericTones: "ku1", Translation: "Chorar", DifficultyLevel: 18},
		{Character: "笑", PinyinWithoutTones: "xiao", PinyinWithTones: "xiào", PinyinWithNumericTones: "xiao4", Translation: "Rir", DifficultyLevel: 18},
		{Character: "说话", PinyinWithoutTones: "shuo hua", PinyinWithTones: "shuō huà", PinyinWithNumericTones: "shuo1 hua4", Translation: "Falar", DifficultyLevel: 18},
		{Character: "不理", PinyinWithoutTones: "bu li", PinyinWithTones: "bù lǐ", PinyinWithNumericTones: "bu4 li3", Translation: "Ignorar", DifficultyLevel: 18},
		{Character: "错", PinyinWithoutTones: "cuo", PinyinWithTones: "cuò", PinyinWithNumericTones: "cuo4", Translation: "Erro", DifficultyLevel: 18},
		{Character: "笨", PinyinWithoutTones: "ben", PinyinWithTones: "bèn", PinyinWithNumericTones: "ben4", Translation: "Bobo", DifficultyLevel: 18},
		{Character: "干", PinyinWithoutTones: "gan", PinyinWithTones: "gàn", PinyinWithNumericTones: "gan4", Translation: "Fazer", DifficultyLevel: 18},
		{Character: "跳舞", PinyinWithoutTones: "tiao wu", PinyinWithTones: "tiào wǔ", PinyinWithNumericTones: "tiao4 wu3", Translation: "Dançar", DifficultyLevel: 18},
		{Character: "带来", PinyinWithoutTones: "dai lai", PinyinWithTones: "dài lái", PinyinWithNumericTones: "dai4 lai2", Translation: "Trazer", DifficultyLevel: 18},
		{Character: "带去", PinyinWithoutTones: "dai qu", PinyinWithTones: "dài qù", PinyinWithNumericTones: "dai4 qu4", Translation: "Levar", DifficultyLevel: 18},
		{Character: "送", PinyinWithoutTones: "song", PinyinWithTones: "sòng", PinyinWithNumericTones: "song4", Translation: "Dar/Entregar", DifficultyLevel: 18},
		{Character: "白酒", PinyinWithoutTones: "bai jiu", PinyinWithTones: "bái jiǔ", PinyinWithNumericTones: "bai2 jiu3", Translation: "Licor branco", DifficultyLevel: 18},
		{Character: "高", PinyinWithoutTones: "gao", PinyinWithTones: "gāo", PinyinWithNumericTones: "gao1", Translation: "Alto", DifficultyLevel: 19},
		{Character: "陈", PinyinWithoutTones: "chen", PinyinWithTones: "chén", PinyinWithNumericTones: "chen2", Translation: "Sobrenome Chen", DifficultyLevel: 19},
		{Character: "如果", PinyinWithoutTones: "ru guo", PinyinWithTones: "rú guǒ", PinyinWithNumericTones: "ru2 guo3", Translation: "Se", DifficultyLevel: 19},
		{Character: "搞错", PinyinWithoutTones: "gao cuo", PinyinWithTones: "gǎo cuò", PinyinWithNumericTones: "gao3 cuo4", Translation: "Errar", DifficultyLevel: 19},
		{Character: "新", PinyinWithoutTones: "xin", PinyinWithTones: "xīn", PinyinWithNumericTones: "xin1", Translation: "Novo", DifficultyLevel: 19},
		{Character: "小学", PinyinWithoutTones: "xiao xue", PinyinWithTones: "xiǎo xué", PinyinWithNumericTones: "xiao3 xue2", Translation: "Escola primária", DifficultyLevel: 19},
		{Character: "啊", PinyinWithoutTones: "a", PinyinWithTones: "a", PinyinWithNumericTones: "a5", Translation: "Ah", DifficultyLevel: 19},
		{Character: "想起来了", PinyinWithoutTones: "xiang qi lai le", PinyinWithTones: "xiǎng qǐ lái le", PinyinWithNumericTones: "xiang3 qi3 lai2 le5", Translation: "Lembrei", DifficultyLevel: 19},
		{Character: "这么", PinyinWithoutTones: "zhe me", PinyinWithTones: "zhè me", PinyinWithNumericTones: "zhe4 me5", Translation: "Tão", DifficultyLevel: 19},
		{Character: "见面", PinyinWithoutTones: "jian mian", PinyinWithTones: "jiàn miàn", PinyinWithNumericTones: "jian4 mian4", Translation: "Encontrar", DifficultyLevel: 19},
		{Character: "认不出", PinyinWithoutTones: "ren bu chu", PinyinWithTones: "rèn bù chū", PinyinWithNumericTones: "ren4 bu4 chu1", Translation: "Não reconhecer", DifficultyLevel: 19},
		{Character: "可不是", PinyinWithoutTones: "ke bu shi", PinyinWithTones: "kě bú shì", PinyinWithNumericTones: "ke3 bu2 shi4", Translation: "Com certeza", DifficultyLevel: 19},
		{Character: "让", PinyinWithoutTones: "rang", PinyinWithTones: "ràng", PinyinWithNumericTones: "rang4", Translation: "Deixar", DifficultyLevel: 19},
		{Character: "介绍", PinyinWithoutTones: "jie shao", PinyinWithTones: "jiè shào", PinyinWithNumericTones: "jie4 shao4", Translation: "Apresentar", DifficultyLevel: 19},
		{Character: "一下", PinyinWithoutTones: "yi xia", PinyinWithTones: "yí xià", PinyinWithNumericTones: "yi2 xia4", Translation: "Um pouco", DifficultyLevel: 19},
		{Character: "荣幸", PinyinWithoutTones: "rong xing", PinyinWithTones: "róng xìng", PinyinWithNumericTones: "rong2 xing4", Translation: "Honrado", DifficultyLevel: 19},
		{Character: "但是", PinyinWithoutTones: "dan shi", PinyinWithTones: "dàn shì", PinyinWithNumericTones: "dan4 shi4", Translation: "Mas", DifficultyLevel: 19},
		{Character: "幼儿园", PinyinWithoutTones: "you er yuan", PinyinWithTones: "yòu ér yuán", PinyinWithNumericTones: "you4 er2 yuan2", Translation: "Jardim de infância", DifficultyLevel: 19},
		{Character: "中学", PinyinWithoutTones: "zhong xue", PinyinWithTones: "zhōng xué", PinyinWithNumericTones: "zhong1 xue2", Translation: "Escola sec.", DifficultyLevel: 19},
		{Character: "学院", PinyinWithoutTones: "xue yuan", PinyinWithTones: "xué yuàn", PinyinWithNumericTones: "xue2 yuan4", Translation: "Faculdade", DifficultyLevel: 19},
		{Character: "大学", PinyinWithoutTones: "da xue", PinyinWithTones: "dà xué", PinyinWithNumericTones: "da4 xue2", Translation: "Universidade", DifficultyLevel: 19},
		{Character: "喂", PinyinWithoutTones: "wei", PinyinWithTones: "wèi", PinyinWithNumericTones: "wei4", Translation: "Alô", DifficultyLevel: 19},
		{Character: "稍等", PinyinWithoutTones: "shao deng", PinyinWithTones: "shāo děng", PinyinWithNumericTones: "shao1 deng3", Translation: "Aguarde", DifficultyLevel: 19},
		{Character: "留下", PinyinWithoutTones: "liu xia", PinyinWithTones: "liú xià", PinyinWithNumericTones: "liu2 xia4", Translation: "Deixar", DifficultyLevel: 19},
		{Character: "马上", PinyinWithoutTones: "ma shang", PinyinWithTones: "mǎ shàng", PinyinWithNumericTones: "ma3 shang4", Translation: "Imediatamente", DifficultyLevel: 19},
		{Character: "就", PinyinWithoutTones: "jiu", PinyinWithTones: "jiù", PinyinWithNumericTones: "jiu4", Translation: "Logo", DifficultyLevel: 19},
		{Character: "位", PinyinWithoutTones: "wei", PinyinWithTones: "wèi", PinyinWithNumericTones: "wei4", Translation: "Classif (pessoa)", DifficultyLevel: 19},
		{Character: "雪", PinyinWithoutTones: "xue", PinyinWithTones: "xuě", PinyinWithNumericTones: "xue3", Translation: "Neve", DifficultyLevel: 19},
		{Character: "能", PinyinWithoutTones: "neng", PinyinWithTones: "néng", PinyinWithNumericTones: "neng2", Translation: "Poder", DifficultyLevel: 19},
		{Character: "想", PinyinWithoutTones: "xiang", PinyinWithTones: "xiǎng", PinyinWithNumericTones: "xiang3", Translation: "Pensar/Querer", DifficultyLevel: 19},
		{Character: "老板", PinyinWithoutTones: "lao ban", PinyinWithTones: "lǎo bǎn", PinyinWithNumericTones: "lao3 ban3", Translation: "Chefe", DifficultyLevel: 19},
		{Character: "查", PinyinWithoutTones: "cha", PinyinWithTones: "chá", PinyinWithNumericTones: "cha2", Translation: "Checar", DifficultyLevel: 19},
		{Character: "常常", PinyinWithoutTones: "chang chang", PinyinWithTones: "cháng cháng", PinyinWithNumericTones: "chang2 chang2", Translation: "Sempre", DifficultyLevel: 19},
		{Character: "关机", PinyinWithoutTones: "guan ji", PinyinWithTones: "guān jī", PinyinWithNumericTones: "guan1 ji1", Translation: "Desligar", DifficultyLevel: 19},
		{Character: "记", PinyinWithoutTones: "ji", PinyinWithTones: "jì", PinyinWithNumericTones: "ji4", Translation: "Anotar", DifficultyLevel: 19},
		{Character: "可以", PinyinWithoutTones: "ke yi", PinyinWithTones: "kě yǐ", PinyinWithNumericTones: "ke3 yi3", Translation: "Poder", DifficultyLevel: 20},
		{Character: "麻烦", PinyinWithoutTones: "ma fan", PinyinWithTones: "má fan", PinyinWithNumericTones: "ma2 fan5", Translation: "Incomodar", DifficultyLevel: 20},
		{Character: "顺着", PinyinWithoutTones: "shun zhe", PinyinWithTones: "shùn zhe", PinyinWithNumericTones: "shun4 zhe5", Translation: "Ao longo de", DifficultyLevel: 20},
		{Character: "路", PinyinWithoutTones: "lu", PinyinWithTones: "lù", PinyinWithNumericTones: "lu4", Translation: "Rua", DifficultyLevel: 20},
		{Character: "一直", PinyinWithoutTones: "yi zhi", PinyinWithTones: "yì zhí", PinyinWithNumericTones: "yi4 zhi2", Translation: "Direto", DifficultyLevel: 20},
		{Character: "往前", PinyinWithoutTones: "wang qian", PinyinWithTones: "wǎng qián", PinyinWithNumericTones: "wang3 qian2", Translation: "Frente", DifficultyLevel: 20},
		{Character: "十字路口", PinyinWithoutTones: "shi zi lu kou", PinyinWithTones: "shí zì lù kǒu", PinyinWithNumericTones: "shi2 zi4 lu4 kou3", Translation: "Cruzamento", DifficultyLevel: 20},
		{Character: "右", PinyinWithoutTones: "you", PinyinWithTones: "yòu", PinyinWithNumericTones: "you4", Translation: "Direita", DifficultyLevel: 20},
		{Character: "左", PinyinWithoutTones: "zuo", PinyinWithTones: "zuǒ", PinyinWithNumericTones: "zuo3", Translation: "Esquerda", DifficultyLevel: 20},
		{Character: "转", PinyinWithoutTones: "zhuan", PinyinWithTones: "zhuǎn", PinyinWithNumericTones: "zhuan3", Translation: "Virar", DifficultyLevel: 20},
		{Character: "然后", PinyinWithoutTones: "ran hou", PinyinWithTones: "rán hòu", PinyinWithNumericTones: "ran2 hou4", Translation: "Depois", DifficultyLevel: 20},
		{Character: "红绿灯", PinyinWithoutTones: "hong lv deng", PinyinWithTones: "hóng lǜ dēng", PinyinWithNumericTones: "hong2 lv4 deng1", Translation: "Semáforo", DifficultyLevel: 20},
		{Character: "对面", PinyinWithoutTones: "dui mian", PinyinWithTones: "duì miàn", PinyinWithNumericTones: "dui4 mian4", Translation: "Oposto", DifficultyLevel: 20},
		{Character: "对", PinyinWithoutTones: "dui", PinyinWithTones: "duì", PinyinWithNumericTones: "dui4", Translation: "Em direção a", DifficultyLevel: 20},
		{Character: "马路", PinyinWithoutTones: "ma lu", PinyinWithTones: "mǎ lù", PinyinWithNumericTones: "ma3 lu4", Translation: "Rua", DifficultyLevel: 20},
		{Character: "小心", PinyinWithoutTones: "xiao xin", PinyinWithTones: "xiǎo xīn", PinyinWithNumericTones: "xiao3 xin1", Translation: "Cuidado", DifficultyLevel: 20},
		{Character: "上边", PinyinWithoutTones: "shang bian", PinyinWithTones: "shàng bian", PinyinWithNumericTones: "shang4 bian5", Translation: "Acima", DifficultyLevel: 20},
		{Character: "下边", PinyinWithoutTones: "xia bian", PinyinWithTones: "xià bian", PinyinWithNumericTones: "xia4 bian5", Translation: "Abaixo", DifficultyLevel: 20},
		{Character: "左边", PinyinWithoutTones: "zuo bian", PinyinWithTones: "zuǒ bian", PinyinWithNumericTones: "zuo3 bian5", Translation: "Lado esquerdo", DifficultyLevel: 20},
		{Character: "右面", PinyinWithoutTones: "you mian", PinyinWithTones: "yòu mian", PinyinWithNumericTones: "you4 mian5", Translation: "Lado direito", DifficultyLevel: 20},
		{Character: "前边", PinyinWithoutTones: "qian bian", PinyinWithTones: "qián bian", PinyinWithNumericTones: "qian2 bian5", Translation: "Na frente", DifficultyLevel: 20},
		{Character: "后边", PinyinWithoutTones: "hou bian", PinyinWithTones: "hòu bian", PinyinWithNumericTones: "hou4 bian5", Translation: "Atrás", DifficultyLevel: 20},
		{Character: "里边", PinyinWithoutTones: "li bian", PinyinWithTones: "lǐ bian", PinyinWithNumericTones: "li3 bian5", Translation: "Dentro", DifficultyLevel: 20},
		{Character: "外边", PinyinWithoutTones: "wai bian", PinyinWithTones: "wài bian", PinyinWithNumericTones: "wai4 bian5", Translation: "Fora", DifficultyLevel: 20},
		{Character: "旁边", PinyinWithoutTones: "pang bian", PinyinWithTones: "páng bian", PinyinWithNumericTones: "pang2 bian5", Translation: "Ao lado", DifficultyLevel: 20},
		{Character: "中间", PinyinWithoutTones: "zhong jian", PinyinWithTones: "zhōng jiān", PinyinWithNumericTones: "zhong1 jian1", Translation: "No meio", DifficultyLevel: 20},
		{Character: "这边", PinyinWithoutTones: "zhe bian", PinyinWithTones: "zhè bian", PinyinWithNumericTones: "zhe4 bian5", Translation: "Aqui/Lado de cá", DifficultyLevel: 20},
		{Character: "折价", PinyinWithoutTones: "zhe jia", PinyinWithTones: "zhé jià", PinyinWithNumericTones: "zhe2 jia4", Translation: "Desconto", DifficultyLevel: 20},
		{Character: "销售", PinyinWithoutTones: "xiao shou", PinyinWithTones: "xiāo shòu", PinyinWithNumericTones: "xiao1 shou4", Translation: "Vender", DifficultyLevel: 20},
		{Character: "价钱", PinyinWithoutTones: "jia qian", PinyinWithTones: "jià qian", PinyinWithNumericTones: "jia4 qian5", Translation: "Preço", DifficultyLevel: 20},
		{Character: "颜色", PinyinWithoutTones: "yan se", PinyinWithTones: "yán sè", PinyinWithNumericTones: "yan2 se4", Translation: "Cor", DifficultyLevel: 20},
		{Character: "红色", PinyinWithoutTones: "hong se", PinyinWithTones: "hóng sè", PinyinWithNumericTones: "hong2 se4", Translation: "Vermelho", DifficultyLevel: 20},
		{Character: "黄色", PinyinWithoutTones: "huang se", PinyinWithTones: "huáng sè", PinyinWithNumericTones: "huang2 se4", Translation: "Amarelo", DifficultyLevel: 20},
		{Character: "蓝色", PinyinWithoutTones: "lan se", PinyinWithTones: "lán sè", PinyinWithNumericTones: "lan2 se4", Translation: "Azul", DifficultyLevel: 20},
		{Character: "穿", PinyinWithoutTones: "chuan", PinyinWithTones: "chuān", PinyinWithNumericTones: "chuan1", Translation: "Vestir", DifficultyLevel: 20},
		{Character: "试衣室", PinyinWithoutTones: "shi yi shi", PinyinWithTones: "shì yī shì", PinyinWithNumericTones: "shi4 yi1 shi4", Translation: "Provador", DifficultyLevel: 20},
		{Character: "那边", PinyinWithoutTones: "na bian", PinyinWithTones: "nà bian", PinyinWithNumericTones: "na4 bian5", Translation: "Lá", DifficultyLevel: 20},
		{Character: "试试", PinyinWithoutTones: "shi shi", PinyinWithTones: "shì shi", PinyinWithNumericTones: "shi4 shi5", Translation: "Tentar", DifficultyLevel: 20},
		{Character: "合适", PinyinWithoutTones: "he shi", PinyinWithTones: "hé shì", PinyinWithNumericTones: "he2 shi4", Translation: "Adequado", DifficultyLevel: 20},
		{Character: "零钱", PinyinWithoutTones: "ling qian", PinyinWithTones: "líng qián", PinyinWithNumericTones: "ling2 qian2", Translation: "Troco", DifficultyLevel: 20},
		{Character: "光顾", PinyinWithoutTones: "guang gu", PinyinWithTones: "guāng gù", PinyinWithNumericTones: "guang1 gu4", Translation: "Visitar", DifficultyLevel: 20},
		{Character: "绿色", PinyinWithoutTones: "lv se", PinyinWithTones: "lǜ sè", PinyinWithNumericTones: "lv4 se4", Translation: "Verde", DifficultyLevel: 20},
		{Character: "灰色", PinyinWithoutTones: "hui se", PinyinWithTones: "huī sè", PinyinWithNumericTones: "hui1 se4", Translation: "Cinza", DifficultyLevel: 20},
		{Character: "粉色", PinyinWithoutTones: "fen se", PinyinWithTones: "fěn sè", PinyinWithNumericTones: "fen3 se4", Translation: "Rosa", DifficultyLevel: 20},
		{Character: "橙色", PinyinWithoutTones: "cheng se", PinyinWithTones: "chéng sè", PinyinWithNumericTones: "cheng2 se4", Translation: "Laranja", DifficultyLevel: 20},
		{Character: "紫色", PinyinWithoutTones: "zi se", PinyinWithTones: "zǐ sè", PinyinWithNumericTones: "zi3 se4", Translation: "Roxo", DifficultyLevel: 20},
		{Character: "银色", PinyinWithoutTones: "yin se", PinyinWithTones: "yín sè", PinyinWithNumericTones: "yin2 se4", Translation: "Prata", DifficultyLevel: 20},
		{Character: "棕色", PinyinWithoutTones: "zong se", PinyinWithTones: "zōng sè", PinyinWithNumericTones: "zong1 se4", Translation: "Marrom", DifficultyLevel: 20},
		{Character: "久", PinyinWithoutTones: "jiu", PinyinWithTones: "jiǔ", PinyinWithNumericTones: "jiu3", Translation: "Longo tempo", DifficultyLevel: 17},
		{Character: "多久", PinyinWithoutTones: "duo jiu", PinyinWithTones: "duō jiǔ", PinyinWithNumericTones: "duo1 jiu3", Translation: "Quanto tempo", DifficultyLevel: 17},
		{Character: "饭店", PinyinWithoutTones: "fan dian", PinyinWithTones: "fàn diàn", PinyinWithNumericTones: "fan4 dian4", Translation: "Restaurante", DifficultyLevel: 17},
		{Character: "等", PinyinWithoutTones: "deng", PinyinWithTones: "děng", PinyinWithNumericTones: "deng3", Translation: "Esperar", DifficultyLevel: 17},
		{Character: "多长时间", PinyinWithoutTones: "duo chang shi jian", PinyinWithTones: "duō cháng shí jiān", PinyinWithNumericTones: "duo1 chang2 shi2 jian1", Translation: "Quanto tempo", DifficultyLevel: 17},
		{Character: "每", PinyinWithoutTones: "mei", PinyinWithTones: "měi", PinyinWithNumericTones: "mei3", Translation: "Cada", DifficultyLevel: 17},
		{Character: "开", PinyinWithoutTones: "kai", PinyinWithTones: "kāi", PinyinWithNumericTones: "kai1", Translation: "Abrir/Dirigir", DifficultyLevel: 17},
		{Character: "晚会", PinyinWithoutTones: "wan hui", PinyinWithTones: "wǎn huì", PinyinWithNumericTones: "wan3 hui4", Translation: "Festa", DifficultyLevel: 17},
		{Character: "看情况", PinyinWithoutTones: "kan qing kuang", PinyinWithTones: "kàn qíng kuàng", PinyinWithNumericTones: "kan4 qing2 kuang4", Translation: "Depende", DifficultyLevel: 17},
		{Character: "生日", PinyinWithoutTones: "sheng ri", PinyinWithTones: "shēng rì", PinyinWithNumericTones: "sheng1 ri4", Translation: "Aniversário", DifficultyLevel: 17},
		{Character: "过生日", PinyinWithoutTones: "guo sheng ri", PinyinWithTones: "guò shēng rì", PinyinWithNumericTones: "guo4 sheng1 ri4", Translation: "Comemorar aniversário", DifficultyLevel: 17},
		{Character: "那么", PinyinWithoutTones: "na me", PinyinWithTones: "nà me", PinyinWithNumericTones: "na4 me5", Translation: "Então", DifficultyLevel: 17},
		{Character: "快", PinyinWithoutTones: "kuai", PinyinWithTones: "kuài", PinyinWithNumericTones: "kuai4", Translation: "Rápido", DifficultyLevel: 17},
		{Character: "又", PinyinWithoutTones: "you", PinyinWithTones: "yòu", PinyinWithNumericTones: "you4", Translation: "Novamente", DifficultyLevel: 17},
		{Character: "离", PinyinWithoutTones: "li", PinyinWithTones: "lí", PinyinWithNumericTones: "li2", Translation: "Longe de", DifficultyLevel: 17},
		{Character: "远", PinyinWithoutTones: "yuan", PinyinWithTones: "yuǎn", PinyinWithNumericTones: "yuan3", Translation: "Longe", DifficultyLevel: 17},
		{Character: "多远", PinyinWithoutTones: "duo yuan", PinyinWithTones: "duō yuǎn", PinyinWithNumericTones: "duo1 yuan3", Translation: "Quão longe", DifficultyLevel: 17},
		{Character: "太", PinyinWithoutTones: "tai", PinyinWithTones: "tài", PinyinWithNumericTones: "tai4", Translation: "Demais", DifficultyLevel: 17},
		{Character: "公里", PinyinWithoutTones: "gong li", PinyinWithTones: "gōng lǐ", PinyinWithNumericTones: "gong1 li3", Translation: "Quilômetro", DifficultyLevel: 17},
		{Character: "从。到", PinyinWithoutTones: "cong dao", PinyinWithTones: "cóng dào", PinyinWithNumericTones: "cong2 dao4", Translation: "De... a...", DifficultyLevel: 17},
		{Character: "公司", PinyinWithoutTones: "gong si", PinyinWithTones: "gōng sī", PinyinWithNumericTones: "gong1 si1", Translation: "Empresa", DifficultyLevel: 17},
		{Character: "要", PinyinWithoutTones: "yao", PinyinWithTones: "yào", PinyinWithNumericTones: "yao4", Translation: "Precisar/Querer", DifficultyLevel: 17},
		{Character: "里约", PinyinWithoutTones: "li yue", PinyinWithTones: "lǐ yuē", PinyinWithNumericTones: "li3 yue1", Translation: "Rio de Janeiro", DifficultyLevel: 17},
		{Character: "圣保罗", PinyinWithoutTones: "sheng bao luo", PinyinWithTones: "shèng bǎo luó", PinyinWithNumericTones: "sheng4 bao3 luo2", Translation: "São Paulo", DifficultyLevel: 17},
		{Character: "画", PinyinWithoutTones: "hua", PinyinWithTones: "huà", PinyinWithNumericTones: "hua4", Translation: "Desenho", DifficultyLevel: 17},
		{Character: "理", PinyinWithoutTones: "li", PinyinWithTones: "lǐ", PinyinWithNumericTones: "li3", Translation: "Cuidar/Arrumar", DifficultyLevel: 17},
		{Character: "头发", PinyinWithoutTones: "tou fa", PinyinWithTones: "tóu fa", PinyinWithNumericTones: "tou2 fa5", Translation: "Cabelo", DifficultyLevel: 17},
		{Character: "检查", PinyinWithoutTones: "jian cha", PinyinWithTones: "jiǎn chá", PinyinWithNumericTones: "jian3 cha2", Translation: "Checar/Examinar", DifficultyLevel: 17},
		{Character: "身体", PinyinWithoutTones: "shen ti", PinyinWithTones: "shēn tǐ", PinyinWithNumericTones: "shen1 ti3", Translation: "Corpo", DifficultyLevel: 17},
		{Character: "父亲", PinyinWithoutTones: "fu qin", PinyinWithTones: "fù qīn", PinyinWithNumericTones: "fu4 qin1", Translation: "Pai", DifficultyLevel: 17},
		{Character: "母亲", PinyinWithoutTones: "mu qin", PinyinWithTones: "mǔ qīn", PinyinWithNumericTones: "mu3 qin1", Translation: "Mãe", DifficultyLevel: 17},
		{Character: "洗澡", PinyinWithoutTones: "xi zao", PinyinWithTones: "xǐ zǎo", PinyinWithNumericTones: "xi3 zao3", Translation: "Tomar banho", DifficultyLevel: 17},
		{Character: "商场", PinyinWithoutTones: "shang chang", PinyinWithTones: "shāng chǎng", PinyinWithNumericTones: "shang1 chang3", Translation: "Shopping", DifficultyLevel: 17},
		{Character: "工厂", PinyinWithoutTones: "gong chang", PinyinWithTones: "gōng chǎng", PinyinWithNumericTones: "gong1 chang3", Translation: "Fábrica", DifficultyLevel: 17},
		{Character: "电影院", PinyinWithoutTones: "dian ying yuan", PinyinWithTones: "diàn yǐng yuàn", PinyinWithNumericTones: "dian4 ying3 yuan4", Translation: "Cinema", DifficultyLevel: 17},
		{Character: "药店", PinyinWithoutTones: "yao dian", PinyinWithTones: "yào diàn", PinyinWithNumericTones: "yao4 dian4", Translation: "Farmácia", DifficultyLevel: 17},
		{Character: "超市", PinyinWithoutTones: "chao shi", PinyinWithTones: "chāo shì", PinyinWithNumericTones: "chao1 shi4", Translation: "Supermercado", DifficultyLevel: 17},
		{Character: "飞机场", PinyinWithoutTones: "fei ji chang", PinyinWithTones: "fēi jī chǎng", PinyinWithNumericTones: "fei1 ji1 chang3", Translation: "Aeroporto", DifficultyLevel: 17},
	}

	log.Println("Iniciando a inserção dos dados de Seed...")
	
	count := 0
	for _, idg := range seedData {
		var existing models.Ideogram
		if err := db.DB.Where("character = ?", idg.Character).First(&existing).Error; err != nil {
			// Se não existir, criamos
			if err := db.DB.Create(&idg).Error; err != nil {
				log.Printf("Erro ao criar ideograma %s: %v", idg.Character, err)
			} else {
				count++
			}
		}
	}

	log.Printf("Seed concluído! %d novos ideogramas foram adicionados.", count)
}
